### ISSUE TITLE
Open redirect on your login page - reported on Reddit

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-flask-best-practices#1]
Reported on [reddit](https://www.reddit.com/r/flask/comments/uefmhl/comment/i6nfive/?utm_source=share&utm_medium=web2x&context=3) - **[You have an open redirect on your login page.](https://github.com/app-generator/sample-flask-best-practices/blob/main/app/auth/routes.py#L37=)**

[Warning: You MUST validate the value of the next parameter. If you do not, your application will be vulnerable to open redirects. For an example implementation of is_safe_url see this Flask Snippet.](https://flask-login.readthedocs.io/en/latest/#login-example)

**Comment by raviwrk-official** [comment]
Added in the safe_url for the open redirect please review the same. :-)

**Comment by app-generator** [comment]
Noted, ty!
